runtime: php
env: flex

runtime_config:
  document_root: .

# [START gae_flex_storage_yaml]
env_variables:
  GOOGLE_STORAGE_BUCKET: pruebatest
  GOOGLE_CLOUD_PROJECT: pruebasydemos-218913
# [END gae_flex_storage_yaml]

application: pruebasydemos-218913
runtime: php


handlers:

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /(.+\.php).*
  script: \1  

- url: /upload
  script: fileimage.php 